create table public.cade_empresa (
  cemp_pk bigint generated by default as identity primary key,
  cemp_nome_fantasia text not null,
  cemp_razao_social text,
  cemp_cnpj text,
  cemp_ie text
);

create table public.cade_mesa (
  cmes_pk bigint generated by default as identity primary key,
  cemp_pk bigint not null references public.cade_empresa(cemp_pk) on delete cascade,
  cmes_numero int not null,
  cmes_status text not null,
  cmes_descricao text
);

create table public.estq_grupo (
  egru_pk bigint generated by default as identity primary key,
  cemp_pk bigint not null references public.cade_empresa(cemp_pk) on delete cascade,
  egru_descricao text not null
);

create table public.estq_produto (
  epro_pk bigint generated by default as identity primary key,
  cemp_pk bigint not null references public.cade_empresa(cemp_pk) on delete cascade,
  egru_pk bigint not null references public.estq_grupo(egru_pk) on delete cascade,
  epro_descricao text not null,
  epro_vlr_varejo decimal not null,
  epro_ativo boolean default true
);

create table public.cade_usuario (
  cusu_pk bigint generated by default as identity,
  cemp_pk bigint not null references public.cade_empresa(cemp_pk) on delete cascade,
  ccot_vend_pk bigint,
  cusu_usuario text not null,
  cusu_senha text,
  primary key (cusu_pk, cemp_pk)
);

create table public.pedi_documentos (
  pdoc_pk bigint generated by default as identity primary key,
  cemp_pk bigint not null,
  cmes_pk bigint references public.cade_mesa(cmes_pk) on delete set null,
  pdoc_dt_emissao timestamp not null,
  pdoc_dt_conclusao timestamp,
  pdoc_status text not null,
  cusu_pk bigint,
  foreign key (cemp_pk) references public.cade_empresa(cemp_pk) on delete cascade,
  foreign key (cusu_pk, cemp_pk) references public.cade_usuario(cusu_pk, cemp_pk) on delete set null
);

create table public.pedi_itens (
  piten_pk bigint generated by default as identity primary key,
  pdoc_pk bigint not null references public.pedi_documentos(pdoc_pk) on delete cascade,
  epro_pk bigint not null references public.estq_produto(epro_pk) on delete cascade,
  piten_qtd int not null,
  piten_obs text,
  piten_status text,
  piten_dt_enviado timestamp
);

create table public.cade_pagamento (
  cpag_pk bigint generated by default as identity primary key,
  cemp_pk bigint not null references public.cade_empresa(cemp_pk) on delete cascade,
  cpag_descricao text not null
);

create table public.flux_documentos_pagamentos (
  fdpa_pk bigint generated by default as identity primary key,
  cemp_pk bigint not null references public.cade_empresa(cemp_pk) on delete cascade,
  cpag_pk bigint not null references public.cade_pagamento(cpag_pk) on delete set null,
  pdoc_pk bigint not null references public.pedi_documentos(pdoc_pk) on delete cascade,
  fdpa_valor decimal not null,
  pago_em timestamp
);
